[package]
name = "lv-metal"
version = "0.1.0"
edition = "2021"
license.workspace = true

[dependencies]
lv-core = { path = "../lv-core" }
candle-core = { git = "https://github.com/Sok205/candle", rev = "235f1e9", features = ["metal"] }
candle-nn = { git = "https://github.com/Sok205/candle", rev = "235f1e9", features = ["metal"] }
candle-transformers = { git = "https://github.com/Sok205/candle", rev = "235f1e9", features = ["metal"] }
tokenizers = "0.21"
tokio = { workspace = true }
async-trait = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
futures = "0.3"
rand = "0.8"
tokio-stream = "0.1"
uuid = { version = "1", features = ["v4"] }
